### ISSUE TITLE
Error loading OS

### ISSUE THREAD

**Issue by Barmallini** [OpenNuvoton/MA35D1_Buildroot#12]
Sometime (frequntly) linux fault in loading with error:
![screenshot1](https://github.com/OpenNuvoton/MA35D1_Buildroot/assets/11353228/ddb81562-5308-4150-b4a7-0ed970e36a78)

Any ideas?

**Comment by ychuang3** [comment]
It could be due to insufficient CPU voltage or issues with the eMMC. Let's first confirm whether you are using a Nuvoton SOM or IoT development board, or something else?

**Comment by Barmallini** [comment]
Iot with bundled power supply unit


вт, 30 янв. 2024 г., 02:57 ychuang3 ***@***.***>:

**Comment by ychuang3** [comment]
For certain versions of the IoT board, there are known issues with CPU voltage. If it is version 2.2 or 2.4, it should be okay; however, other versions might experience problems with insufficient CPU voltage. The CPU voltage should be >= 1.25V. Please check with the distributor or Nuvoton FAE to confirm and obtain assistance for your IoT board.

**Comment by Barmallini** [comment]
My board v2.3
Is it bad?
I'm experienced with soldering, tell me please what to do.


вт, 30 янв. 2024 г., 03:05 ychuang3 ***@***.***>:

**Comment by ychuang3** [comment]
![image](https://github.com/OpenNuvoton/MA35D1_Buildroot/assets/70507205/30cbd24a-0b4d-4bae-85af-1e093eb68d78)

replace R5  24K  with 26.1K

**Comment by Barmallini** [comment]
Worked.

It's solves 2 problems with one shot:
1. Random reboot at loading
2. Loosing connection during Ethernet transfer

Thanks!


вт, 30 янв. 2024 г., 10:14 ychuang3 ***@***.***>:
