### ISSUE TITLE
Debugger for m4 core

### ISSUE THREAD

**Issue by Barmallini** [OpenNuvoton/MA35D1_Buildroot#13]
Please, provide "blink" example and short instruction how to upload and debug code (cortex m4)

I have nulink2 pro debugger interface and numaker-iot-ma35d16f90

**Comment by Michael050492** [comment]
Hi,
Regarding how to upload and debug code,
I saw the debug configuration for Cortex-A and Cortex-M from "NuEclipse User Manual".
Hope this helps.

[https://www.nuvoton.com/tool-and-software/ide-and-compiler/]

**Comment by Barmallini** [comment]
Actually, I need step by step solution how to run and debug M4 code with already running Linux onboard.
I suppose to upload binary firmware from SD card to address 0 and run it.
Next step somehow connect with debugger to M4 core, put breakpoint and start step by step debugging.

**Comment by ychuang3** [comment]
![image](https://github.com/OpenNuvoton/MA35D1_Buildroot/assets/70507205/c69c2304-ffb1-465e-b912-d3c8a443b8d7)

Please find the following pins from your Nulink2 Pro ICE:
- VSS (GND)
- ICEDAT
- ICECLK
- nRESET

And then connect to the ICE connector, pin number shown as above.

Like this:

![image](https://github.com/OpenNuvoton/MA35D1_Buildroot/assets/70507205/6608bee5-1282-4fe4-95c4-39814dbb8329)

Start Linux ...
Open RTP BSP sample code Keil project. 
Compile project and then you enter debug mode directly from the Keil IDE debug button.

**Comment by Barmallini** [comment]
No luck with NuEclipse

Open On-Chip Debugger 0.12.0.024.1+dev-00166-g9699f57c6 (2024-01-26-06:26)
Licensed under GNU GPL v2
For bug reports, read
    http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
Info : auto-selecting first available session transport "swd". To override use 'transport select <transport>'.
Info : Hardware thread awareness created
Info : Hardware thread awareness created
Started by GNU ARM Eclipse
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : Using CMSIS-DAPv2 interface with VID:PID=0x0416:0x2005, serial=13010000002900F10144BD9900000A80
Info : CMSIS-DAP: SWD supported
Info : CMSIS-DAP: JTAG supported
Info : CMSIS-DAP: SWO-UART supported
Info : CMSIS-DAP: Atomic commands supported
Info : CMSIS-DAP: UART communication port supported
Info : CMSIS-DAP: UART via USB COM port supported
Info : CMSIS-DAP: FW Version = 2.1.0
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 1 TDO = 1 nTRST = 0 nRESET = 1
Info : CMSIS-DAP: Interface ready
Info : clock speed 1000 kHz
Error: Error connecting DP: cannot read IDR

![2mBvu9lxIfcUSLuN](https://github.com/OpenNuvoton/MA35D1_Buildroot/assets/11353228/a0838749-080a-48dd-af75-c1b1ba6c1085)
![7nmhtFssq1yz5Hvg](https://github.com/OpenNuvoton/MA35D1_Buildroot/assets/11353228/436f608c-2a24-4ee6-8c6d-cebbdfaaa833)
![uHWfCW4rWYDWhqtU](https://github.com/OpenNuvoton/MA35D1_Buildroot/assets/11353228/fab93bcd-4381-4a25-9321-5ae9fa5bd7d3)

**Comment by Barmallini** [comment]
Any suggestions for Nueclipse configuration?
Working environment is Linux, so Keil is useless.

**Comment by ychuang3** [comment]
M4 is independent of Linux.
I am using Keil for downloading and debugging M4 code while running Linux.
It works pretty well. It's the most convenient and efficient way to debug M4.
Please try running any sample code from the MA35D1 RTP BSP. (https://github.com/OpenNuvoton/MA35D1_RTP_BSP)

**Comment by Barmallini** [comment]
Problem not in sample code. I'm unable to connect/upload code to m4 core
Error: Error connecting DP: cannot read IDR

**Comment by ychuang3** [comment]
The sample code project had properly select the ICE debugger.
Can you please try again with RTP BSP sample code project?

**Comment by Barmallini** [comment]
NuLink connects now (with soldering iron, R42 and R43 mus be bridged). SWD socket was disconnected by default... Funny...
![nuvoton_sj](https://github.com/OpenNuvoton/MA35D1_Buildroot/assets/11353228/7d0db92a-f963-4b78-8d2e-ed8003908bfa)
