### ISSUE TITLE
Debug M4 core under Linux not working

### ISSUE THREAD

**Issue by Barmallini** [OpenNuvoton/MA35D1_Buildroot#15]
Expected:
Start Linux ...
Open RTP BSP sample code NuEclipse project.
Compile project and then you enter debug mode directly from the NuEclipse IDE debug button.
Step by step debugging...
--------------------------------------------------------------------------------------------------
By fact (first configuration):
1. Start board ...
2. Start Linux ... wait for loading to prompt...
3. Open RTP BSP sample code NuEclipse project.
4. Compile project, start debug and then you have:

Open On-Chip Debugger 0.12.0.024.1+dev-00166-g9699f57c6 (2024-01-26-06:26)
Licensed under GNU GPL v2
For bug reports, read
http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
Info : auto-selecting first available session transport "swd". To override use 'transport select '.
Info : Hardware thread awareness created
Info : Hardware thread awareness created
Started by GNU ARM Eclipse
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : Using CMSIS-DAPv2 interface with VID:PID=0x0416:0x2005, serial=xxxxxxxxxx
Info : CMSIS-DAP: SWD supported
Info : CMSIS-DAP: JTAG supported
Info : CMSIS-DAP: SWO-UART supported
Info : CMSIS-DAP: Atomic commands supported
Info : CMSIS-DAP: UART communication port supported
Info : CMSIS-DAP: UART via USB COM port supported
Info : CMSIS-DAP: FW Version = 2.1.0
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 1 TDO = 1 nTRST = 0 nRESET = 1
Info : CMSIS-DAP: Interface ready
Info : clock speed 1000 kHz
Error: Error connecting DP: cannot read IDR

By fact (second configuration):
1. Open RTP BSP sample code NuEclipse project.
2. Compile project, 
3. Start board ...
4. Start Linux ... immediately (it's important) start debugging session

All run as expected, step by step debugging work fine, Linux continue to loading, BUT if stop debugger after Linux loading complete and run it again we have:
Error: Error connecting DP: cannot read IDR

By fact (third configuration):
1. Start board ...
2. Start Linux ... wait for loading to U=Boot and stop here...
3. Open RTP BSP sample code NuEclipse project.
4. Compile project, start debug and then you have:

All run as expected, step by step debugging work fine

**Question:**
What happened after Linux loading with SWD (pins of SWD)?
Linux reconfigure it to something else?

**Comment by ychuang3** [comment]
Your description is very detailed. 

The ICE SWD pins of RTP M4 are using PG.12 and PG.13.

If you are using the NuMaker-SOM board, then the EBI will be using PG.12 and PG.13. However, the BSP default does not enable EBI, so if you enable EBI manually, it will take away the functionality of PG.12 and PG.13, causing the M4 unable to use ICE.

If you are using the NuMake-IoT board, then I2S0 will be using PG.12 and PG.13, and the BSP default enables I2S0. Therefore, please disable I2S0, and this should solve the problem.

**Comment by Barmallini** [comment]
That's helps.
We are disable I2S0 in dts file and now it's working fine!

Thanks!
