### ISSUE TITLE
Buildroot SPI for Linux

### ISSUE THREAD

**Issue by Barmallini** [OpenNuvoton/MA35D1_Buildroot#19]
Unable to add spi0 and spi2 to Linux.
Added status OK to dts, but no spi devices in ls /dev

Found this example:
http://forum.nuvoton.com/viewtopic.php?t=11238

I need raw spi

**Comment by cwweng-nuvoton** [comment]
Please modify Linux Kernel configuration and device tree to generate spi0 and spi2 devices in /dev

1. Enable Kernel config CONFIG_SPI_SPIDEV
![image](https://github.com/user-attachments/assets/dfbedb91-d3a8-4340-bcc3-4572c75606f0)

2. Set spidev node of spi0 and spi2 in device tree 
![image](https://github.com/user-attachments/assets/faade5d5-1e9c-48dd-a02c-ba7778da654a)


3. Rebuild and boot Linux Kernel.  spidev1.1 and spidev2.1 are generated in /dev 
![image](https://github.com/user-attachments/assets/306efa15-ae88-4e75-b7a9-54e9675807be)

**Comment by Barmallini** [comment]
compatible = "spidev", default driver?

**Comment by cwweng-nuvoton** [comment]
compatible = "spidev";  is also fine.
Following is another sample 
![image](https://github.com/user-attachments/assets/d4764e21-9495-4a99-81f3-2c5c503e36ab)
It can generate /dev/spidev1.0, /dev/spidev2.0 for spi0 and spi2 respectively.
![image](https://github.com/user-attachments/assets/27b23d02-28a9-4f68-92c9-9bab213b20d6)

**Comment by Barmallini** [comment]
Not sure about <reg> value
Spidev arrived to /dev, but spi not working.
Maybe CS misconfigured?

![IMG_20240719_080655_749](https://github.com/user-attachments/assets/c1a1b99f-a6da-4663-a96d-895856d8331a)

![IMG_20240719_080701_270](https://github.com/user-attachments/assets/4be958a8-b116-45bd-80d3-edad0b8d6eaa)

**Comment by Barmallini** [comment]
Most valuable information taked from ST wiki:

https://wiki.st.com/stm32mpu/wiki/SPI_device_tree_configuration

**Comment by Barmallini** [comment]
Actually, SPI start working. Issue with DMA. Better to say - it works with DMA (disabled by default in dts) and do not work without DMA (loose 1 byte in transaction and stuck in infinity loop, RXFIFO empty)
