### ISSUE TITLE
SPI transfer hangs

### ISSUE THREAD

**Issue by Barmallini** [OpenNuvoton/MA35D1_Buildroot#21]
SPI interface, master mode, full-duplex.
Transferring 150 bytes, it hangs after receiving 149 bytes.
Driver spi-ma35d1-spi.c , line 629.

Any ideas?

Attached screen from LA, CS never goes up.
![IMG_20240904_200421_765](https://github.com/user-attachments/assets/7b5d2d4a-79c9-4788-8fea-a1fc299edac6)

**Comment by Barmallini** [comment]
Fixed by taking driver from buildroot 2024

**Comment by ychuang3** [comment]
This Buildroot (2021) and Buildroot 2024 are using the same Linux kernel, and of course, the drivers are the same as well. You probably haven't updated the kernel yet. Please follow the steps below to update and recompile:
```
# make linux-dirclean
# rm -rf dl/linux
# make linux-rebuild
```

**Comment by Barmallini** [comment]
Actually moved to Buildroot 2024. All fine now!
