### ISSUE TITLE
nuc980 chilli board have fixed mac ids.

### ISSUE THREAD

**Issue by MrutyunjayPatel** [OpenNuvoton/MA35D1_Buildroot#9]
hi, 
we have built the latest uboot and kernel files using current buildroot.
we also able to enable Telnet service on the boards also enable dhcp on boot. 

yesterday we got the second board "Chilli board"  for evaluation.
 
we flashed the second board with the kernel v5.10 built image file sets uboot, env  uimage and dbt files.
the second board booted fine.

when we checked the ip and mac of the second board its same as the first board.

Chilli board1 :  08:00:27:00:01:93
Chilli board2 :  08:00:27:00:01:93

we tried setting second board with different mac id with uboot env  "ethaddr=08:00:27:00:01:94"
and save the settings to flash,  hoping the on next power off-on cycle the new mac id will be set to second board.

**how we set the mac id of the boards to different values?**  

on both the devices the mac address read are same .

~ # cat ./sys/devices/platform/ahb/b0022000.emac1/net/eth0/address 
08:00:27:00:01:93

we do have our own mac id series, will be needing option to load our own mac-id to final production boards.

**Comment by yclu-ntc** [comment]
Hi, 

You can feed MAC address to each EMAC driver by adding the following command to env file:

`bootargs=root=/dev/ram0 console=ttyS0,115200n8 rdinit=/sbin/init mem=64M lpj=744448, ethaddr1=YOUR_MAC_ADDR`

The arguments are "ethaddr0" for emac0, and "ethaddr1" for emac1.

**Comment by MrutyunjayPatel** [comment]
hi ,
Thanks we could set the board mac id,

how and from where did the board get the default mac id as "08:00:27:00:01:93"

is it possible to set the custom default mac id if the env does not have it configured.

also how will the production devices mac id to be set to , is their any tool ( production/factory) to do the requirement.

**Comment by ychuang3** [comment]
NUC980 has no flash to store MAC address information.
It's suggested to increase the MAC address setting in env.txt when you are programming NUC980 images to NAND, SD, or SPI.

**Comment by MrutyunjayPatel** [comment]
hi, 
Thanks very much.
